### ISSUE TITLE
Segfault when running the image example

### ISSUE THREAD

**Issue by Eijebong** [emoon/rust_minifb#186]
Environnment: Archlinux, i3(X11).

To repro: `cargo build --examples` and then `./target/debug/examples/image`

GDB Output:
```
(gdb) thr apply all bt

Thread 1 (Thread 0x7ffff7bc59c0 (LWP 334046)):
#0  0x00005555556036bd in Image_center (target=<optimized out>, source=<optimized out>, w=512, h=<optimized out>, s=<optimized out>, window_width=<optimized out>, window_height=174, bg_clear=0) at src/native/unix/scalar.cpp:117
#1  0x00005555555e82d0 in minifb::os::unix::x11::Window::raw_blit_buffer (self=0x7fffffff8cc0, buffer=..., buf_width=512, buf_height=512, buf_stride=512) at src/os/unix/x11.rs:826
#2  0x00005555555e7caf in minifb::os::unix::x11::Window::update_with_buffer_stride (self=0x7fffffff8cc0, buffer=..., buf_width=512, buf_height=512, buf_stride=512) at src/os/unix/x11.rs:540
#3  0x00005555555d4d98 in minifb::os::unix::Window::update_with_buffer_stride (self=0x7fffffff8cb8, buffer=..., buf_width=512, buf_height=512, buf_stride=512) at src/os/unix/mod.rs:78
#4  0x0000555555580cef in minifb::Window::update_with_buffer (self=0x7fffffff8cb8, buffer=..., width=512, height=512) at /home/eijebong/code/rust_minifb/src/lib.rs:295
#5  0x0000555555580723 in image::main () at examples/image.rs:35
```

ASAN Output:
```
=================================================================
==331754==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fc4115bb874 at pc 0x5601af0c2b17 bp 0x7ffd9c61aa20 sp 0x7ffd9c61aa18
WRITE of size 4 at 0x7fc4115bb874 thread T0
    #0 0x5601af0c2b16 in Image_center /home/eijebong/code/rust_minifb/src/native/unix/scalar.cpp:117:31
    #1 0x5601af0531c3 in minifb::os::unix::x11::Window::raw_blit_buffer::h0524a668cad0675b /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:826:17
    #2 0x5601af052326 in minifb::os::unix::x11::Window::update_with_buffer_stride::h18b062d85242e5a0 /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:540:18
    #3 0x5601af015d34 in minifb::os::unix::Window::update_with_buffer_stride::hba756f7988ccecd4 /home/eijebong/code/rust_minifb/src/os/unix/mod.rs:78:17
    #4 0x5601aeeb6c2d in minifb::Window::update_with_buffer::h19e0ff2e2f4f4b8b /home/eijebong/code/rust_minifb/src/lib.rs:295:9
    #5 0x5601aeeb630c in image::main::hf736df520dff0169 /home/eijebong/code/rust_minifb/examples/image.rs:35:9
    #6 0x5601aeeaedb0 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h0741f52c2888f755 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67:34
    #7 0x5601af516d18 in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h7c7701ace7781644 /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/rt.rs:52:13
    #8 0x5601af516d18 in std::panicking::try::do_call::h25761ef781a3cec3 /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:297:40
    #9 0x5601af516d18 in std::panicking::try::hc2ed2ebc2df17cc1 /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panicking.rs:274:15
    #10 0x5601af516d18 in std::panic::catch_unwind::h548ef5f09b7c73ca /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/panic.rs:394:14
    #11 0x5601af516d18 in std::rt::lang_start_internal::h9a98dc8e2c22711e /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libstd/rt.rs:51:25
    #12 0x5601aeeaed24 in std::rt::lang_start::h05d27abd606c41ac /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67:5
    #13 0x5601aeeb67d9 in main (/home/eijebong/code/rust_minifb/target/debug/examples/image+0x1177d9)
    #14 0x7fc41503a022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)
    #15 0x5601aee0d28d in _start (/home/eijebong/code/rust_minifb/target/debug/examples/image+0x6e28d)

0x7fc4115bb874 is located 116 bytes to the right of 2097152-byte region [0x7fc4113bb800,0x7fc4115bb800)
allocated by thread T0 here:
    #0 0x5601aee79839 in realloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cc:164:3
    #1 0x5601af1ac909 in alloc::alloc::realloc::he6ec84f468887cb2 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/alloc.rs:124:5
    #2 0x5601af1acf85 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..AllocRef$GT$::grow::h476ac121b955ed30 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/alloc.rs:218:27
    #3 0x5601af1b07c3 in alloc::raw_vec::finish_grow::h578e7f4f2dcb751d /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:491:18
    #4 0x5601af1b2bac in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_amortized::h6f1424c4272f2bd9 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:420:22
    #5 0x5601af1b1d6c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve::hc5a3f74c00954e9e /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/raw_vec.rs:281:13
    #6 0x5601af1b7037 in alloc::vec::Vec$LT$T$GT$::reserve::h39b73455bdee72b3 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:500:9
    #7 0x5601af0856d3 in alloc::vec::Vec$LT$T$GT$::resize::hea306af84c1dfb53 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1559:13
    #8 0x5601af051a2e in minifb::os::unix::x11::Window::alloc_image::h7922508db1882a86 /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:491:9
    #9 0x5601af054f42 in minifb::os::unix::x11::Window::raw_process_one_event::h07068902d4beb215 /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:948:31
    #10 0x5601af054533 in minifb::os::unix::x11::Window::raw_process_events::ha0afce57f68c6bc4 /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:904:16
    #11 0x5601af052694 in minifb::os::unix::x11::Window::update::hfa358fdb57e4a436 /home/eijebong/code/rust_minifb/src/os/unix/x11.rs:556:13
    #12 0x5601af015d34 in minifb::os::unix::Window::update_with_buffer_stride::hba756f7988ccecd4 /home/eijebong/code/rust_minifb/src/os/unix/mod.rs:78:17
    #13 0x5601aeeb6c2d in minifb::Window::update_with_buffer::h19e0ff2e2f4f4b8b /home/eijebong/code/rust_minifb/src/lib.rs:295:9
    #14 0x5601aeeb630c in image::main::hf736df520dff0169 /home/eijebong/code/rust_minifb/examples/image.rs:35:9
    #15 0x5601aeeaedb0 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h0741f52c2888f755 /home/eijebong/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67:34
    #16 0x5601aeeb67d9 in main (/home/eijebong/code/rust_minifb/target/debug/examples/image+0x1177d9)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/eijebong/code/rust_minifb/src/native/unix/scalar.cpp:117:31 in Image_center
Shadow bytes around the buggy address:
  0x0ff9022af6b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9022af6c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9022af6d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9022af6e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff9022af6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff9022af700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa
  0x0ff9022af710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff9022af720: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff9022af730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff9022af740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff9022af750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==331754==ABORTING
```

**Comment by emoon** [comment]
Thanks for the report. Should be fixed in the latest git version

**Comment by Eijebong** [comment]
It is :)
