### ISSUE TITLE
Linux: Scale::X8 and larger causes panic on `Window::update_with_buffer`

### ISSUE THREAD

**Issue by mateon1** [emoon/rust_minifb#80]
To reproduce:

1. Create a window 64 pixels wide and 32 pixels tall, with scale set to 8x
2. Call `window.update_with_buffer(&[0; 64 * 32]);`
3. Observe the panic:

```gdb
thread 'main' panicked at 'bad scale for raw_blit_buffer()', /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/minifb-0.12.0/src/os/unix/mod.rs:629:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/07e0c3651ce2a7b326f7678e135d8d5bbbbe5d18/src/libstd/panicking.rs:411
   8: minifb::os::unix::Window::raw_blit_buffer
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/minifb-0.12.0/src/os/unix/mod.rs:629
   9: minifb::os::unix::Window::update_with_buffer
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/minifb-0.12.0/src/os/unix/mod.rs:417
  10: minifb::Window::update_with_buffer
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/minifb-0.12.0/src/lib.rs:236
  11: concrete_interpreter::ConcreteMachine::new
             at src/concrete-interpreter.rs:34
  12: concrete_interpreter::main
             at src/concrete-interpreter.rs:91
  13: std::rt::lang_start::{{closure}}
             at /rustc/07e0c3651ce2a7b326f7678e135d8d5bbbbe5d18/src/libstd/rt.rs:64
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: std::rt::lang_start
             at /rustc/07e0c3651ce2a7b326f7678e135d8d5bbbbe5d18/src/libstd/rt.rs:64
  21: main
  22: __libc_start_main
  23: _start
```

**Comment by mateon1** [comment]
Nevermind, this was just fixed in commit e20257db793bef59d62abe29dcd9b5408dd1f20d.
This is just not published to crates.io yet.

Closing.

**Comment by emoon** [comment]
I will make sure to publish a new version today to include the fix.

**Comment by emoon** [comment]
0.13 has been release now
